// <auto-generated />
using Comanda.Api;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Comanda.Api.Migrations
{
    [DbContext(typeof(ComandasDBContext))]
    partial class ComandasDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.21");

            modelBuilder.Entity("Comanda.Api.Models.CardapioItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("PossuiPreparo")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Preco")
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CardapioItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Hambúrguer clássico com queijo, alface, tomate e molho especial.",
                            PossuiPreparo = true,
                            Preco = 20m,
                            Titulo = "Hambúrguer Clássico"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Refrigerante gelado de 350ml para acompanhar sua refeição.",
                            PossuiPreparo = false,
                            Preco = 5m,
                            Titulo = "Refrigerante 350ml"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Porção de batatas fritas crocantes e douradas.",
                            PossuiPreparo = true,
                            Preco = 10m,
                            Titulo = "Batatas Fritas"
                        });
                });

            modelBuilder.Entity("Comanda.Api.Models.Comanda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumeroMesa")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Comandas");
                });

            modelBuilder.Entity("Comanda.Api.Models.ComandaItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CardapioItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComandaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ComandaId");

                    b.ToTable("ComandaItems");
                });

            modelBuilder.Entity("Comanda.Api.Models.Mesa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumeroMesa")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SituacaoMesa")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Mesas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NumeroMesa = 1,
                            SituacaoMesa = 0
                        },
                        new
                        {
                            Id = 2,
                            NumeroMesa = 2,
                            SituacaoMesa = 0
                        },
                        new
                        {
                            Id = 3,
                            NumeroMesa = 3,
                            SituacaoMesa = 0
                        });
                });

            modelBuilder.Entity("Comanda.Api.Models.PedidoCozinha", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComandaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ComandaId");

                    b.ToTable("PedidoCozinhas");
                });

            modelBuilder.Entity("Comanda.Api.Models.PedidoCozinhaItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComandaItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PedidoCozinhaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ComandaItemId");

                    b.HasIndex("PedidoCozinhaId");

                    b.ToTable("PedidoCozinhaItens");
                });

            modelBuilder.Entity("Comanda.Api.Models.Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumeroMesa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("Comanda.Api.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@admin",
                            Nome = "Admin",
                            Senha = "admin123"
                        });
                });

            modelBuilder.Entity("Comanda.Api.Models.ComandaItem", b =>
                {
                    b.HasOne("Comanda.Api.Models.Comanda", "Comanda")
                        .WithMany("Itens")
                        .HasForeignKey("ComandaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comanda");
                });

            modelBuilder.Entity("Comanda.Api.Models.PedidoCozinha", b =>
                {
                    b.HasOne("Comanda.Api.Models.Comanda", "Comanda")
                        .WithMany()
                        .HasForeignKey("ComandaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comanda");
                });

            modelBuilder.Entity("Comanda.Api.Models.PedidoCozinhaItem", b =>
                {
                    b.HasOne("Comanda.Api.Models.ComandaItem", "ComandaItem")
                        .WithMany()
                        .HasForeignKey("ComandaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Comanda.Api.Models.PedidoCozinha", "PedidoCozinha")
                        .WithMany("Itens")
                        .HasForeignKey("PedidoCozinhaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComandaItem");

                    b.Navigation("PedidoCozinha");
                });

            modelBuilder.Entity("Comanda.Api.Models.Comanda", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("Comanda.Api.Models.PedidoCozinha", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
